// ============================================================
//  PlayerData.js - 玩家战机数据表
//  所有玩家飞机属性、技能在此集中配置，方便平衡性调整
// ============================================================

export const PlayerData = {
  sf01: {
    id: 'sf01',
    name: '猎鹰 FALCON',
    desc: '均衡型：新手友好，综合全面',
    maxHp: 100,
    speed: 6,
    hitboxR: 4,
    grazeR: 24,
    startBomb: 3,
    bombDamage: 600,
    bombInvuln: 1500, // ms
    ultName: '激光扫射',
    passive: '击杀回复能量+5%',
    energyRegenKillsBonus: 0.05,
    // 各火力等级的武器配置
    weapons: [
      // lv1
      { shots: [{angle: -Math.PI/2, offset: 0, speed: 10, damage: 1, color: 'cyan'}] },
      // lv2
      { shots: [
        {angle: -Math.PI/2, offset: -8,  speed: 10, damage: 1, color: 'cyan'},
        {angle: -Math.PI/2, offset:  8,  speed: 10, damage: 1, color: 'cyan'},
      ]},
      // lv3 + 僚机1
      { shots: [
        {angle: -Math.PI/2, offset: -10, speed: 11, damage: 1.2, color: 'cyan'},
        {angle: -Math.PI/2, offset:  10, speed: 11, damage: 1.2, color: 'cyan'},
        {angle: -Math.PI/2 - 0.08, offset: -18, speed: 9, damage: 0.8, color: 'cyan'},
        {angle: -Math.PI/2 + 0.08, offset:  18, speed: 9, damage: 0.8, color: 'cyan'},
      ], wingmen: 1},
      // lv4
      { shots: [
        {angle: -Math.PI/2, offset: -10, speed: 12, damage: 1.4, color: 'cyan'},
        {angle: -Math.PI/2, offset:  10, speed: 12, damage: 1.4, color: 'cyan'},
        {angle: -Math.PI/2 - 0.12, offset: -22, speed: 10, damage: 1.0, color: 'cyan'},
        {angle: -Math.PI/2 + 0.12, offset:  22, speed: 10, damage: 1.0, color: 'cyan'},
      ], wingmen: 1},
      // lv5 + 僚机2
      { shots: [
        {angle: -Math.PI/2, offset: -14, speed: 13, damage: 1.6, color: 'cyan'},
        {angle: -Math.PI/2, offset:  0,  speed: 13, damage: 1.8, color: 'cyan'},
        {angle: -Math.PI/2, offset:  14, speed: 13, damage: 1.6, color: 'cyan'},
        {angle: -Math.PI/2 - 0.18, offset: -28, speed: 11, damage: 1.2, color: 'cyan'},
        {angle: -Math.PI/2 + 0.18, offset:  28, speed: 11, damage: 1.2, color: 'cyan'},
      ], wingmen: 2},
      // lv6
      { shots: [
        {angle: -Math.PI/2, offset: -16, speed: 13, damage: 1.8, color: 'cyan'},
        {angle: -Math.PI/2, offset:  0,  speed: 14, damage: 2.0, color: 'cyan'},
        {angle: -Math.PI/2, offset:  16, speed: 13, damage: 1.8, color: 'cyan'},
        {angle: -Math.PI/2 - 0.2, offset: -30, speed: 12, damage: 1.4, color: 'cyan'},
        {angle: -Math.PI/2 + 0.2, offset:  30, speed: 12, damage: 1.4, color: 'cyan'},
        {angle: -Math.PI/2 - 0.35, offset: -40, speed: 10, damage: 1.0, color: 'cyan'},
        {angle: -Math.PI/2 + 0.35, offset:  40, speed: 10, damage: 1.0, color: 'cyan'},
      ], wingmen: 2},
      // lv7
      { shots: [
        {angle: -Math.PI/2, offset: -18, speed: 14, damage: 2.0, color: 'cyan'},
        {angle: -Math.PI/2, offset:  0,  speed: 15, damage: 2.5, color: 'cyan'},
        {angle: -Math.PI/2, offset:  18, speed: 14, damage: 2.0, color: 'cyan'},
        {angle: -Math.PI/2 - 0.2, offset: -32, speed: 13, damage: 1.6, color: 'cyan'},
        {angle: -Math.PI/2 + 0.2, offset:  32, speed: 13, damage: 1.6, color: 'cyan'},
        {angle: -Math.PI/2 - 0.4, offset: -44, speed: 11, damage: 1.2, color: 'cyan'},
        {angle: -Math.PI/2 + 0.4, offset:  44, speed: 11, damage: 1.2, color: 'cyan'},
      ], wingmen: 2, pierce: 1},
      // lv8 金色穿透
      { shots: [
        {angle: -Math.PI/2, offset: -20, speed: 15, damage: 2.6, color: 'gold'},
        {angle: -Math.PI/2, offset:  0,  speed: 16, damage: 3.0, color: 'gold'},
        {angle: -Math.PI/2, offset:  20, speed: 15, damage: 2.6, color: 'gold'},
        {angle: -Math.PI/2 - 0.22, offset: -36, speed: 14, damage: 2.0, color: 'gold'},
        {angle: -Math.PI/2 + 0.22, offset:  36, speed: 14, damage: 2.0, color: 'gold'},
        {angle: -Math.PI/2 - 0.42, offset: -50, speed: 12, damage: 1.6, color: 'gold'},
        {angle: -Math.PI/2 + 0.42, offset:  50, speed: 12, damage: 1.6, color: 'gold'},
      ], wingmen: 2, pierce: 3, max: true},
    ],
    charge: { time: 1500, damage: 40, size: 12 },
  },

  sf02: {
    id: 'sf02',
    name: '雷霆 THUNDER',
    desc: '火力型：单发伤害爆表，移动慢',
    maxHp: 120,
    speed: 4.2,
    hitboxR: 5,
    grazeR: 22,
    startBomb: 2,
    bombDamage: 900,
    bombInvuln: 1600,
    ultName: '电磁脉冲',
    passive: '蓄力攻击伤害+30%',
    chargeDamageBonus: 0.3,
    weapons: [
      { shots: [{angle: -Math.PI/2, offset: 0, speed: 8.5, damage: 1.6, color: 'gold', size: 5}] },
      { shots: [{angle: -Math.PI/2, offset: -10, speed: 8.5, damage: 1.6, color: 'gold', size: 5},
                {angle: -Math.PI/2, offset:  10, speed: 8.5, damage: 1.6, color: 'gold', size: 5}] },
      { shots: [{angle: -Math.PI/2, offset: -12, speed: 9, damage: 2.0, color: 'gold', size: 5},
                {angle: -Math.PI/2, offset:  12, speed: 9, damage: 2.0, color: 'gold', size: 5},
                {angle: -Math.PI/2 - 0.1, offset: -26, speed: 8, damage: 1.4, color: 'gold', size: 4}], wingmen: 1},
      { shots: [{angle: -Math.PI/2, offset: -14, speed: 9, damage: 2.2, color: 'gold', size: 5},
                {angle: -Math.PI/2, offset:  14, speed: 9, damage: 2.2, color: 'gold', size: 5},
                {angle: -Math.PI/2, offset: -30, speed: 8, damage: 1.6, color: 'gold', size: 4},
                {angle: -Math.PI/2, offset:  30, speed: 8, damage: 1.6, color: 'gold', size: 4}], wingmen: 1},
      { shots: [{angle: -Math.PI/2, offset: -14, speed: 10, damage: 2.6, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset:  0,  speed: 10, damage: 2.8, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset:  14, speed: 10, damage: 2.6, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset: -30, speed: 9, damage: 1.8, color: 'gold', size: 4},
                {angle: -Math.PI/2, offset:  30, speed: 9, damage: 1.8, color: 'gold', size: 4}], wingmen: 2},
      { shots: [{angle: -Math.PI/2, offset: -16, speed: 10, damage: 3.0, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset:  0,  speed: 11, damage: 3.4, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset:  16, speed: 10, damage: 3.0, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset: -32, speed: 10, damage: 2.2, color: 'gold', size: 5},
                {angle: -Math.PI/2, offset:  32, speed: 10, damage: 2.2, color: 'gold', size: 5},
                {angle: -Math.PI/2 - 0.08, offset: -46, speed: 9, damage: 1.6, color: 'gold', size: 4},
                {angle: -Math.PI/2 + 0.08, offset:  46, speed: 9, damage: 1.6, color: 'gold', size: 4}], wingmen: 2},
      { shots: [{angle: -Math.PI/2, offset: -18, speed: 11, damage: 3.4, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset:  0,  speed: 12, damage: 4.0, color: 'gold', size: 7},
                {angle: -Math.PI/2, offset:  18, speed: 11, damage: 3.4, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset: -34, speed: 11, damage: 2.6, color: 'gold', size: 5},
                {angle: -Math.PI/2, offset:  34, speed: 11, damage: 2.6, color: 'gold', size: 5},
                {angle: -Math.PI/2 - 0.12, offset: -48, speed: 10, damage: 2.0, color: 'gold', size: 5},
                {angle: -Math.PI/2 + 0.12, offset:  48, speed: 10, damage: 2.0, color: 'gold', size: 5}], wingmen: 2, pierce: 2},
      { shots: [{angle: -Math.PI/2, offset: -20, speed: 12, damage: 4.0, color: 'gold', size: 7},
                {angle: -Math.PI/2, offset:  0,  speed: 13, damage: 5.0, color: 'gold', size: 8},
                {angle: -Math.PI/2, offset:  20, speed: 12, damage: 4.0, color: 'gold', size: 7},
                {angle: -Math.PI/2, offset: -36, speed: 12, damage: 3.2, color: 'gold', size: 6},
                {angle: -Math.PI/2, offset:  36, speed: 12, damage: 3.2, color: 'gold', size: 6},
                {angle: -Math.PI/2 - 0.15, offset: -52, speed: 11, damage: 2.6, color: 'gold', size: 5},
                {angle: -Math.PI/2 + 0.15, offset:  52, speed: 11, damage: 2.6, color: 'gold', size: 5}], wingmen: 2, pierce: 5, max: true},
    ],
    charge: { time: 1500, damage: 60, size: 16 },
  },

  sf03: {
    id: 'sf03',
    name: '幻影 PHANTOM',
    desc: '技巧型：移动快，擦弹加分',
    maxHp: 80,
    speed: 9,
    hitboxR: 3,
    grazeR: 30,
    startBomb: 4,
    bombDamage: 500,
    bombInvuln: 2000,
    ultName: '时停领域',
    passive: '擦弹+额外分数/能量；必杀时间减速3s',
    grazeBonus: 1.5,
    slowmoOnBomb: 3000,
    weapons: [
      { shots: [{angle: -Math.PI/2, offset: -6, speed: 12, damage: 0.9, color: 'purple', homing: 0.2},
                {angle: -Math.PI/2, offset:  6, speed: 12, damage: 0.9, color: 'purple', homing: 0.2}] },
      { shots: [{angle: -Math.PI/2, offset: -8, speed: 12, damage: 1.0, color: 'purple', homing: 0.22},
                {angle: -Math.PI/2, offset:  8, speed: 12, damage: 1.0, color: 'purple', homing: 0.22}] },
      { shots: [{angle: -Math.PI/2, offset: -10, speed: 13, damage: 1.1, color: 'purple', homing: 0.25},
                {angle: -Math.PI/2, offset:  0,  speed: 13, damage: 1.1, color: 'purple', homing: 0.25},
                {angle: -Math.PI/2, offset:  10, speed: 13, damage: 1.1, color: 'purple', homing: 0.25}], wingmen: 1},
      { shots: [{angle: -Math.PI/2, offset: -12, speed: 13, damage: 1.2, color: 'purple', homing: 0.28},
                {angle: -Math.PI/2, offset:  0,  speed: 13, damage: 1.2, color: 'purple', homing: 0.28},
                {angle: -Math.PI/2, offset:  12, speed: 13, damage: 1.2, color: 'purple', homing: 0.28},
                {angle: -Math.PI/2 - 0.2, offset: -24, speed: 11, damage: 0.8, color: 'purple', homing: 0.3},
                {angle: -Math.PI/2 + 0.2, offset:  24, speed: 11, damage: 0.8, color: 'purple', homing: 0.3}], wingmen: 1},
      { shots: [{angle: -Math.PI/2, offset: -14, speed: 14, damage: 1.3, color: 'purple', homing: 0.3},
                {angle: -Math.PI/2, offset:  0,  speed: 14, damage: 1.4, color: 'purple', homing: 0.3},
                {angle: -Math.PI/2, offset:  14, speed: 14, damage: 1.3, color: 'purple', homing: 0.3},
                {angle: -Math.PI/2 - 0.2, offset: -26, speed: 12, damage: 1.0, color: 'purple', homing: 0.33},
                {angle: -Math.PI/2 + 0.2, offset:  26, speed: 12, damage: 1.0, color: 'purple', homing: 0.33},
                {angle: -Math.PI/2 - 0.4, offset: -38, speed: 11, damage: 0.8, color: 'purple', homing: 0.36},
                {angle: -Math.PI/2 + 0.4, offset:  38, speed: 11, damage: 0.8, color: 'purple', homing: 0.36}], wingmen: 2},
      { shots: [{angle: -Math.PI/2, offset: -16, speed: 14, damage: 1.4, color: 'purple', homing: 0.33},
                {angle: -Math.PI/2, offset:  0,  speed: 15, damage: 1.6, color: 'purple', homing: 0.33},
                {angle: -Math.PI/2, offset:  16, speed: 14, damage: 1.4, color: 'purple', homing: 0.33},
                {angle: -Math.PI/2 - 0.22, offset: -28, speed: 13, damage: 1.2, color: 'purple', homing: 0.36},
                {angle: -Math.PI/2 + 0.22, offset:  28, speed: 13, damage: 1.2, color: 'purple', homing: 0.36},
                {angle: -Math.PI/2 - 0.42, offset: -42, speed: 12, damage: 1.0, color: 'purple', homing: 0.4},
                {angle: -Math.PI/2 + 0.42, offset:  42, speed: 12, damage: 1.0, color: 'purple', homing: 0.4}], wingmen: 2},
      { shots: [{angle: -Math.PI/2, offset: -18, speed: 15, damage: 1.6, color: 'purple', homing: 0.36},
                {angle: -Math.PI/2, offset:  0,  speed: 16, damage: 1.8, color: 'purple', homing: 0.36},
                {angle: -Math.PI/2, offset:  18, speed: 15, damage: 1.6, color: 'purple', homing: 0.36},
                {angle: -Math.PI/2 - 0.25, offset: -32, speed: 14, damage: 1.4, color: 'purple', homing: 0.4},
                {angle: -Math.PI/2 + 0.25, offset:  32, speed: 14, damage: 1.4, color: 'purple', homing: 0.4},
                {angle: -Math.PI/2 - 0.5, offset: -46, speed: 13, damage: 1.2, color: 'purple', homing: 0.44},
                {angle: -Math.PI/2 + 0.5, offset:  46, speed: 13, damage: 1.2, color: 'purple', homing: 0.44}], wingmen: 2, pierce: 2},
      { shots: [{angle: -Math.PI/2, offset: -20, speed: 16, damage: 1.8, color: 'purple', homing: 0.4},
                {angle: -Math.PI/2, offset:  0,  speed: 17, damage: 2.0, color: 'purple', homing: 0.4},
                {angle: -Math.PI/2, offset:  20, speed: 16, damage: 1.8, color: 'purple', homing: 0.4},
                {angle: -Math.PI/2 - 0.28, offset: -36, speed: 15, damage: 1.6, color: 'purple', homing: 0.44},
                {angle: -Math.PI/2 + 0.28, offset:  36, speed: 15, damage: 1.6, color: 'purple', homing: 0.44},
                {angle: -Math.PI/2 - 0.55, offset: -50, speed: 14, damage: 1.4, color: 'purple', homing: 0.48},
                {angle: -Math.PI/2 + 0.55, offset:  50, speed: 14, damage: 1.4, color: 'purple', homing: 0.48}], wingmen: 2, pierce: 4, max: true},
    ],
    charge: { time: 1300, damage: 35, size: 10, homingShots: 8 }, // 蓄力额外8发追踪
  }
};

export const MAX_POWER = 8;
export default PlayerData;
