// ============================================================
//  TankData.js - 坦克属性表（玩家/敌方）
// ============================================================

export const PlayerTanks = {
  scholar: {
    id: 'scholar',
    name: '学霸号',
    desc: '蓝色·知识 — 蓄力炮',
    maxHp: 3,
    speed: 2.0,
    fireRate: 400,
    bulletSpeed: 6,
    bulletDamage: 1,
    bulletType: 'normal',
    maxBullets: 2,
    color: '#00aaff',
    skill: 'charge',
    chargeTime: 1200,
    chargeDamage: 3,
    chargeRadius: 16,
  },
  athlete: {
    id: 'athlete',
    name: '体育生',
    desc: '橙色·活力 — 冲刺',
    maxHp: 4,
    speed: 3.0,
    fireRate: 350,
    bulletSpeed: 5,
    bulletDamage: 1,
    bulletType: 'spread3',
    maxBullets: 2,
    color: '#ff8800',
    skill: 'dash',
    dashTime: 300,
    dashCD: 4000,
  },
  artist: {
    id: 'artist',
    name: '文艺委员',
    desc: '紫色·优雅 — 护盾',
    maxHp: 2,
    speed: 2.2,
    fireRate: 450,
    bulletSpeed: 7,
    bulletDamage: 1,
    bulletType: 'pierce',
    maxBullets: 2,
    color: '#aa00ff',
    skill: 'shield',
    shieldTime: 3000,
    shieldCD: 8000,
  },
};

export const PlayerTankList = ['scholar', 'athlete', 'artist'];

export const EnemyTanks = {
  scout: {
    id: 'scout',
    name: '新生',
    hp: 1,
    speed: 1.2,
    fireRate: 1500,
    bulletSpeed: 3,
    bulletDamage: 1,
    bulletType: 'normal',
    maxBullets: 1,
    score: 100,
    color: '#888888',
    ai: 'patrol',
  },
  striker: {
    id: 'striker',
    name: '突击兵',
    hp: 2,
    speed: 1.8,
    fireRate: 1000,
    bulletSpeed: 4,
    bulletDamage: 1,
    bulletType: 'normal',
    maxBullets: 1,
    score: 200,
    color: '#ff4444',
    ai: 'chase',
  },
  heavy: {
    id: 'heavy',
    name: '重装',
    hp: 4,
    speed: 0.8,
    fireRate: 2000,
    bulletSpeed: 3,
    bulletDamage: 2,
    bulletType: 'heavy',
    maxBullets: 1,
    score: 300,
    color: '#446644',
    ai: 'guard',
  },
  sniper: {
    id: 'sniper',
    name: '狙击手',
    hp: 1,
    speed: 1.5,
    fireRate: 1800,
    bulletSpeed: 8,
    bulletDamage: 1,
    bulletType: 'normal',
    maxBullets: 1,
    score: 250,
    color: '#ffdd00',
    ai: 'ambush',
  },
  boss: {
    id: 'boss',
    name: 'Boss坦克',
    hp: 10,
    speed: 1.5,
    fireRate: 800,
    bulletSpeed: 4,
    bulletDamage: 1,
    bulletType: 'spread3',
    maxBullets: 3,
    score: 2000,
    color: '#ff00ff',
    ai: 'boss',
    phases: 3,
    size: 1.5,
  },
  suicide: {
    id: 'suicide',
    name: '自爆兵',
    hp: 1,
    speed: 2.6,
    fireRate: 9999,
    bulletSpeed: 0,
    bulletDamage: 0,
    bulletType: 'normal',
    maxBullets: 0,
    score: 200,
    color: '#ff2200',
    ai: 'suicide',
  },
  golden: {
    id: 'golden',
    name: '金坦克',
    hp: 1,
    speed: 2.2,
    fireRate: 1800,
    bulletSpeed: 4,
    bulletDamage: 1,
    bulletType: 'normal',
    maxBullets: 1,
    score: 1000,
    color: '#ffd700',
    ai: 'patrol',
  },
};

export const PowerupData = {
  star:   { name: '火力升级', color: '#fff200', icon: '★', duration: 0 },
  speed:  { name: '速度提升', color: '#00ff88', icon: '⚡', duration: 10000 },
  shield: { name: '护盾',     color: '#00f0ff', icon: '◇', duration: 8000 },
  heart:  { name: '加生命',   color: '#ff3366', icon: '♥', duration: 0 },
  bomb:   { name: '炸弹',     color: '#ff8800', icon: '✦', duration: 0 },
  freeze: { name: '冻结',     color: '#88ccff', icon: '❄', duration: 5000 },
  base:   { name: '基地加固', color: '#ffaa00', icon: '⌂', duration: 10000 },
  random: { name: '随机空投', color: '#ff00d4', icon: '?', duration: 0 },
  airstrike: { name: '空袭支援', color: '#ff4444', icon: 'A', duration: 0 },
  rapid:     { name: '急速射击', color: '#00ffcc', icon: 'R', duration: 10000 },
};

export const PowerupTypes = ['star', 'speed', 'shield', 'heart', 'bomb', 'freeze', 'base', 'random', 'airstrike', 'rapid'];

export const RankThresholds = {
  S: 0.95,
  A: 0.80,
  B: 0.60,
  C: 0.40,
  D: 0.00,
};
